//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ServiciosSoap")]
    public interface ServiciosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Filtros_Extensiones", ReplyAction="*")]
        Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse Filtros_Extensiones(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Filtros_Extensiones", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse> Filtros_ExtensionesAsync(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Filtros_ExtensionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Filtros_Extensiones", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequestBody Body;
        
        public Filtros_ExtensionesRequest() {
        }
        
        public Filtros_ExtensionesRequest(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Filtros_ExtensionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipo;
        
        public Filtros_ExtensionesRequestBody() {
        }
        
        public Filtros_ExtensionesRequestBody(string tipo) {
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Filtros_ExtensionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Filtros_ExtensionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponseBody Body;
        
        public Filtros_ExtensionesResponse() {
        }
        
        public Filtros_ExtensionesResponse(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Filtros_ExtensionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Filtros_ExtensionesResult;
        
        public Filtros_ExtensionesResponseBody() {
        }
        
        public Filtros_ExtensionesResponseBody(string Filtros_ExtensionesResult) {
            this.Filtros_ExtensionesResult = Filtros_ExtensionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiciosSoapChannel : Bodega_Ventas.ServiceReference1.ServiciosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiciosSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceReference1.ServiciosSoap>, Bodega_Ventas.ServiceReference1.ServiciosSoap {
        
        public ServiciosSoapClient() {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiciosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse Bodega_Ventas.ServiceReference1.ServiciosSoap.Filtros_Extensiones(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest request) {
            return base.Channel.Filtros_Extensiones(request);
        }
        
        public string Filtros_Extensiones(string tipo) {
            Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest inValue = new Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest();
            inValue.Body = new Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequestBody();
            inValue.Body.tipo = tipo;
            Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse retVal = ((Bodega_Ventas.ServiceReference1.ServiciosSoap)(this)).Filtros_Extensiones(inValue);
            return retVal.Body.Filtros_ExtensionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse> Bodega_Ventas.ServiceReference1.ServiciosSoap.Filtros_ExtensionesAsync(Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest request) {
            return base.Channel.Filtros_ExtensionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceReference1.Filtros_ExtensionesResponse> Filtros_ExtensionesAsync(string tipo) {
            Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest inValue = new Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequest();
            inValue.Body = new Bodega_Ventas.ServiceReference1.Filtros_ExtensionesRequestBody();
            inValue.Body.tipo = tipo;
            return ((Bodega_Ventas.ServiceReference1.ServiciosSoap)(this)).Filtros_ExtensionesAsync(inValue);
        }
    }
}
