//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceClientes {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceClientes.ClientesSoap")]
    public interface ClientesSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.HelloWorldResponse HelloWorld(Bodega_Ventas.ServiceClientes.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServiceClientes.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.InsertarClienteResponse InsertarCliente(Bodega_Ventas.ServiceClientes.InsertarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.InsertarClienteResponse> InsertarClienteAsync(Bodega_Ventas.ServiceClientes.InsertarClienteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ContarClientesActivosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContarClientesActivos", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse ContarClientesActivos(Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContarClientesActivos", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse> ContarClientesActivosAsync(Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ContarClientesEliminadosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContarClientesEliminados", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse ContarClientesEliminados(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ContarClientesEliminados", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse> ContarClientesEliminadosAsync(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento RestaurarClientesEliminadosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestaurarClientesEliminados", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse RestaurarClientesEliminados(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RestaurarClientesEliminados", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse> RestaurarClientesEliminadosAsync(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombres del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarCliente", ReplyAction="*")]
        Bodega_Ventas.ServiceClientes.EditarClienteResponse EditarCliente(Bodega_Ventas.ServiceClientes.EditarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.EditarClienteResponse> EditarClienteAsync(Bodega_Ventas.ServiceClientes.EditarClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdCliente", ReplyAction="*")]
        int ObtenerIdCliente();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdCliente", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerIdClienteAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServiceClientes.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServiceClientes.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCliente", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.InsertarClienteRequestBody Body;
        
        public InsertarClienteRequest() {
        }
        
        public InsertarClienteRequest(Bodega_Ventas.ServiceClientes.InsertarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string genero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string movil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] foto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string numico;
        
        public InsertarClienteRequestBody() {
        }
        
        public InsertarClienteRequestBody(string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.fecha = fecha;
            this.genero = genero;
            this.tipo = tipo;
            this.correo = correo;
            this.direccion = direccion;
            this.ruc = ruc;
            this.movil = movil;
            this.telefono = telefono;
            this.foto = foto;
            this.numico = numico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.InsertarClienteResponseBody Body;
        
        public InsertarClienteResponse() {
        }
        
        public InsertarClienteResponse(Bodega_Ventas.ServiceClientes.InsertarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarClienteResult;
        
        public InsertarClienteResponseBody() {
        }
        
        public InsertarClienteResponseBody(string InsertarClienteResult) {
            this.InsertarClienteResult = InsertarClienteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContarClientesActivosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContarClientesActivos", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.ContarClientesActivosRequestBody Body;
        
        public ContarClientesActivosRequest() {
        }
        
        public ContarClientesActivosRequest(Bodega_Ventas.ServiceClientes.ContarClientesActivosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ContarClientesActivosRequestBody {
        
        public ContarClientesActivosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContarClientesActivosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContarClientesActivosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.ContarClientesActivosResponseBody Body;
        
        public ContarClientesActivosResponse() {
        }
        
        public ContarClientesActivosResponse(Bodega_Ventas.ServiceClientes.ContarClientesActivosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContarClientesActivosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ContarClientesActivosResult;
        
        public ContarClientesActivosResponseBody() {
        }
        
        public ContarClientesActivosResponseBody(string ContarClientesActivosResult) {
            this.ContarClientesActivosResult = ContarClientesActivosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContarClientesEliminadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContarClientesEliminados", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequestBody Body;
        
        public ContarClientesEliminadosRequest() {
        }
        
        public ContarClientesEliminadosRequest(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ContarClientesEliminadosRequestBody {
        
        public ContarClientesEliminadosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ContarClientesEliminadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ContarClientesEliminadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponseBody Body;
        
        public ContarClientesEliminadosResponse() {
        }
        
        public ContarClientesEliminadosResponse(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ContarClientesEliminadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ContarClientesEliminadosResult;
        
        public ContarClientesEliminadosResponseBody() {
        }
        
        public ContarClientesEliminadosResponseBody(string ContarClientesEliminadosResult) {
            this.ContarClientesEliminadosResult = ContarClientesEliminadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestaurarClientesEliminadosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestaurarClientesEliminados", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequestBody Body;
        
        public RestaurarClientesEliminadosRequest() {
        }
        
        public RestaurarClientesEliminadosRequest(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RestaurarClientesEliminadosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idcli;
        
        public RestaurarClientesEliminadosRequestBody() {
        }
        
        public RestaurarClientesEliminadosRequestBody(int idcli) {
            this.idcli = idcli;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RestaurarClientesEliminadosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RestaurarClientesEliminadosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponseBody Body;
        
        public RestaurarClientesEliminadosResponse() {
        }
        
        public RestaurarClientesEliminadosResponse(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RestaurarClientesEliminadosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RestaurarClientesEliminadosResult;
        
        public RestaurarClientesEliminadosResponseBody() {
        }
        
        public RestaurarClientesEliminadosResponseBody(string RestaurarClientesEliminadosResult) {
            this.RestaurarClientesEliminadosResult = RestaurarClientesEliminadosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarCliente", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.EditarClienteRequestBody Body;
        
        public EditarClienteRequest() {
        }
        
        public EditarClienteRequest(Bodega_Ventas.ServiceClientes.EditarClienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarClienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idcli;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombres;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string apellidos;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string genero;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int tipo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string correo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string direccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string ruc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string movil;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string telefono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public byte[] foto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string numico;
        
        public EditarClienteRequestBody() {
        }
        
        public EditarClienteRequestBody(int idcli, string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            this.idcli = idcli;
            this.nombres = nombres;
            this.apellidos = apellidos;
            this.fecha = fecha;
            this.genero = genero;
            this.tipo = tipo;
            this.correo = correo;
            this.direccion = direccion;
            this.ruc = ruc;
            this.movil = movil;
            this.telefono = telefono;
            this.foto = foto;
            this.numico = numico;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditarClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditarClienteResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceClientes.EditarClienteResponseBody Body;
        
        public EditarClienteResponse() {
        }
        
        public EditarClienteResponse(Bodega_Ventas.ServiceClientes.EditarClienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditarClienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EditarClienteResult;
        
        public EditarClienteResponseBody() {
        }
        
        public EditarClienteResponseBody(string EditarClienteResult) {
            this.EditarClienteResult = EditarClienteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ClientesSoapChannel : Bodega_Ventas.ServiceClientes.ClientesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ClientesSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceClientes.ClientesSoap>, Bodega_Ventas.ServiceClientes.ClientesSoap {
        
        public ClientesSoapClient() {
        }
        
        public ClientesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ClientesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ClientesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.HelloWorldResponse Bodega_Ventas.ServiceClientes.ClientesSoap.HelloWorld(Bodega_Ventas.ServiceClientes.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServiceClientes.HelloWorldRequest inValue = new Bodega_Ventas.ServiceClientes.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.HelloWorldRequestBody();
            Bodega_Ventas.ServiceClientes.HelloWorldResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.HelloWorldResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.HelloWorldAsync(Bodega_Ventas.ServiceClientes.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServiceClientes.HelloWorldRequest inValue = new Bodega_Ventas.ServiceClientes.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.InsertarClienteResponse Bodega_Ventas.ServiceClientes.ClientesSoap.InsertarCliente(Bodega_Ventas.ServiceClientes.InsertarClienteRequest request) {
            return base.Channel.InsertarCliente(request);
        }
        
        public string InsertarCliente(string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            Bodega_Ventas.ServiceClientes.InsertarClienteRequest inValue = new Bodega_Ventas.ServiceClientes.InsertarClienteRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.InsertarClienteRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.fecha = fecha;
            inValue.Body.genero = genero;
            inValue.Body.tipo = tipo;
            inValue.Body.correo = correo;
            inValue.Body.direccion = direccion;
            inValue.Body.ruc = ruc;
            inValue.Body.movil = movil;
            inValue.Body.telefono = telefono;
            inValue.Body.foto = foto;
            inValue.Body.numico = numico;
            Bodega_Ventas.ServiceClientes.InsertarClienteResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).InsertarCliente(inValue);
            return retVal.Body.InsertarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.InsertarClienteResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.InsertarClienteAsync(Bodega_Ventas.ServiceClientes.InsertarClienteRequest request) {
            return base.Channel.InsertarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.InsertarClienteResponse> InsertarClienteAsync(string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            Bodega_Ventas.ServiceClientes.InsertarClienteRequest inValue = new Bodega_Ventas.ServiceClientes.InsertarClienteRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.InsertarClienteRequestBody();
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.fecha = fecha;
            inValue.Body.genero = genero;
            inValue.Body.tipo = tipo;
            inValue.Body.correo = correo;
            inValue.Body.direccion = direccion;
            inValue.Body.ruc = ruc;
            inValue.Body.movil = movil;
            inValue.Body.telefono = telefono;
            inValue.Body.foto = foto;
            inValue.Body.numico = numico;
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).InsertarClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse Bodega_Ventas.ServiceClientes.ClientesSoap.ContarClientesActivos(Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest request) {
            return base.Channel.ContarClientesActivos(request);
        }
        
        public string ContarClientesActivos() {
            Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest inValue = new Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.ContarClientesActivosRequestBody();
            Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).ContarClientesActivos(inValue);
            return retVal.Body.ContarClientesActivosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.ContarClientesActivosAsync(Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest request) {
            return base.Channel.ContarClientesActivosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesActivosResponse> ContarClientesActivosAsync() {
            Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest inValue = new Bodega_Ventas.ServiceClientes.ContarClientesActivosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.ContarClientesActivosRequestBody();
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).ContarClientesActivosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse Bodega_Ventas.ServiceClientes.ClientesSoap.ContarClientesEliminados(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest request) {
            return base.Channel.ContarClientesEliminados(request);
        }
        
        public string ContarClientesEliminados() {
            Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest inValue = new Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequestBody();
            Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).ContarClientesEliminados(inValue);
            return retVal.Body.ContarClientesEliminadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.ContarClientesEliminadosAsync(Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest request) {
            return base.Channel.ContarClientesEliminadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.ContarClientesEliminadosResponse> ContarClientesEliminadosAsync() {
            Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest inValue = new Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.ContarClientesEliminadosRequestBody();
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).ContarClientesEliminadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse Bodega_Ventas.ServiceClientes.ClientesSoap.RestaurarClientesEliminados(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest request) {
            return base.Channel.RestaurarClientesEliminados(request);
        }
        
        public string RestaurarClientesEliminados(int idcli) {
            Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest inValue = new Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequestBody();
            inValue.Body.idcli = idcli;
            Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).RestaurarClientesEliminados(inValue);
            return retVal.Body.RestaurarClientesEliminadosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.RestaurarClientesEliminadosAsync(Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest request) {
            return base.Channel.RestaurarClientesEliminadosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosResponse> RestaurarClientesEliminadosAsync(int idcli) {
            Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest inValue = new Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.RestaurarClientesEliminadosRequestBody();
            inValue.Body.idcli = idcli;
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).RestaurarClientesEliminadosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceClientes.EditarClienteResponse Bodega_Ventas.ServiceClientes.ClientesSoap.EditarCliente(Bodega_Ventas.ServiceClientes.EditarClienteRequest request) {
            return base.Channel.EditarCliente(request);
        }
        
        public string EditarCliente(int idcli, string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            Bodega_Ventas.ServiceClientes.EditarClienteRequest inValue = new Bodega_Ventas.ServiceClientes.EditarClienteRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.EditarClienteRequestBody();
            inValue.Body.idcli = idcli;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.fecha = fecha;
            inValue.Body.genero = genero;
            inValue.Body.tipo = tipo;
            inValue.Body.correo = correo;
            inValue.Body.direccion = direccion;
            inValue.Body.ruc = ruc;
            inValue.Body.movil = movil;
            inValue.Body.telefono = telefono;
            inValue.Body.foto = foto;
            inValue.Body.numico = numico;
            Bodega_Ventas.ServiceClientes.EditarClienteResponse retVal = ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).EditarCliente(inValue);
            return retVal.Body.EditarClienteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.EditarClienteResponse> Bodega_Ventas.ServiceClientes.ClientesSoap.EditarClienteAsync(Bodega_Ventas.ServiceClientes.EditarClienteRequest request) {
            return base.Channel.EditarClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceClientes.EditarClienteResponse> EditarClienteAsync(int idcli, string nombres, string apellidos, System.DateTime fecha, string genero, int tipo, string correo, string direccion, string ruc, string movil, string telefono, byte[] foto, string numico) {
            Bodega_Ventas.ServiceClientes.EditarClienteRequest inValue = new Bodega_Ventas.ServiceClientes.EditarClienteRequest();
            inValue.Body = new Bodega_Ventas.ServiceClientes.EditarClienteRequestBody();
            inValue.Body.idcli = idcli;
            inValue.Body.nombres = nombres;
            inValue.Body.apellidos = apellidos;
            inValue.Body.fecha = fecha;
            inValue.Body.genero = genero;
            inValue.Body.tipo = tipo;
            inValue.Body.correo = correo;
            inValue.Body.direccion = direccion;
            inValue.Body.ruc = ruc;
            inValue.Body.movil = movil;
            inValue.Body.telefono = telefono;
            inValue.Body.foto = foto;
            inValue.Body.numico = numico;
            return ((Bodega_Ventas.ServiceClientes.ClientesSoap)(this)).EditarClienteAsync(inValue);
        }
        
        public int ObtenerIdCliente() {
            return base.Channel.ObtenerIdCliente();
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdClienteAsync() {
            return base.Channel.ObtenerIdClienteAsync();
        }
    }
}
