//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServicePedidos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePedidos.PedidosSoap")]
    public interface PedidosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServicePedidos.HelloWorldResponse HelloWorld(Bodega_Ventas.ServicePedidos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServicePedidos.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombrecat del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdCategoria", ReplyAction="*")]
        Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse ObtenerIdCategoria(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdCategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse> ObtenerIdCategoriaAsync(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdPedido", ReplyAction="*")]
        int ObtenerIdPedido(int caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdPedido", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerIdPedidoAsync(int caja);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServicePedidos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServicePedidos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServicePedidos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServicePedidos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIdCategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIdCategoria", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequestBody Body;
        
        public ObtenerIdCategoriaRequest() {
        }
        
        public ObtenerIdCategoriaRequest(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIdCategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombrecat;
        
        public ObtenerIdCategoriaRequestBody() {
        }
        
        public ObtenerIdCategoriaRequestBody(string nombrecat) {
            this.nombrecat = nombrecat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerIdCategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerIdCategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponseBody Body;
        
        public ObtenerIdCategoriaResponse() {
        }
        
        public ObtenerIdCategoriaResponse(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerIdCategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ObtenerIdCategoriaResult;
        
        public ObtenerIdCategoriaResponseBody() {
        }
        
        public ObtenerIdCategoriaResponseBody(int ObtenerIdCategoriaResult) {
            this.ObtenerIdCategoriaResult = ObtenerIdCategoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PedidosSoapChannel : Bodega_Ventas.ServicePedidos.PedidosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PedidosSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServicePedidos.PedidosSoap>, Bodega_Ventas.ServicePedidos.PedidosSoap {
        
        public PedidosSoapClient() {
        }
        
        public PedidosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PedidosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PedidosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServicePedidos.HelloWorldResponse Bodega_Ventas.ServicePedidos.PedidosSoap.HelloWorld(Bodega_Ventas.ServicePedidos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServicePedidos.HelloWorldRequest inValue = new Bodega_Ventas.ServicePedidos.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServicePedidos.HelloWorldRequestBody();
            Bodega_Ventas.ServicePedidos.HelloWorldResponse retVal = ((Bodega_Ventas.ServicePedidos.PedidosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.HelloWorldResponse> Bodega_Ventas.ServicePedidos.PedidosSoap.HelloWorldAsync(Bodega_Ventas.ServicePedidos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServicePedidos.HelloWorldRequest inValue = new Bodega_Ventas.ServicePedidos.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServicePedidos.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServicePedidos.PedidosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse Bodega_Ventas.ServicePedidos.PedidosSoap.ObtenerIdCategoria(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest request) {
            return base.Channel.ObtenerIdCategoria(request);
        }
        
        public int ObtenerIdCategoria(string nombrecat) {
            Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest inValue = new Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest();
            inValue.Body = new Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequestBody();
            inValue.Body.nombrecat = nombrecat;
            Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse retVal = ((Bodega_Ventas.ServicePedidos.PedidosSoap)(this)).ObtenerIdCategoria(inValue);
            return retVal.Body.ObtenerIdCategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse> Bodega_Ventas.ServicePedidos.PedidosSoap.ObtenerIdCategoriaAsync(Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest request) {
            return base.Channel.ObtenerIdCategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaResponse> ObtenerIdCategoriaAsync(string nombrecat) {
            Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest inValue = new Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequest();
            inValue.Body = new Bodega_Ventas.ServicePedidos.ObtenerIdCategoriaRequestBody();
            inValue.Body.nombrecat = nombrecat;
            return ((Bodega_Ventas.ServicePedidos.PedidosSoap)(this)).ObtenerIdCategoriaAsync(inValue);
        }
        
        public int ObtenerIdPedido(int caja) {
            return base.Channel.ObtenerIdPedido(caja);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdPedidoAsync(int caja) {
            return base.Channel.ObtenerIdPedidoAsync(caja);
        }
    }
}
