//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceVentas {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceVentas.VentasSoap")]
    public interface VentasSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServiceVentas.HelloWorldResponse HelloWorld(Bodega_Ventas.ServiceVentas.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceVentas.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServiceVentas.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdVenta", ReplyAction="*")]
        int ObtenerIdVenta(int caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerIdVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ObtenerIdVentaAsync(int caja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarVenta", ReplyAction="*")]
        bool ProcesarVenta(int idCliente, int idUsuario, int idCaja);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ProcesarVenta", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> ProcesarVentaAsync(int idCliente, int idUsuario, int idCaja);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceVentas.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServiceVentas.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceVentas.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServiceVentas.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VentasSoapChannel : Bodega_Ventas.ServiceVentas.VentasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentasSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceVentas.VentasSoap>, Bodega_Ventas.ServiceVentas.VentasSoap {
        
        public VentasSoapClient() {
        }
        
        public VentasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceVentas.HelloWorldResponse Bodega_Ventas.ServiceVentas.VentasSoap.HelloWorld(Bodega_Ventas.ServiceVentas.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServiceVentas.HelloWorldRequest inValue = new Bodega_Ventas.ServiceVentas.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceVentas.HelloWorldRequestBody();
            Bodega_Ventas.ServiceVentas.HelloWorldResponse retVal = ((Bodega_Ventas.ServiceVentas.VentasSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceVentas.HelloWorldResponse> Bodega_Ventas.ServiceVentas.VentasSoap.HelloWorldAsync(Bodega_Ventas.ServiceVentas.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceVentas.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServiceVentas.HelloWorldRequest inValue = new Bodega_Ventas.ServiceVentas.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceVentas.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServiceVentas.VentasSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int ObtenerIdVenta(int caja) {
            return base.Channel.ObtenerIdVenta(caja);
        }
        
        public System.Threading.Tasks.Task<int> ObtenerIdVentaAsync(int caja) {
            return base.Channel.ObtenerIdVentaAsync(caja);
        }
        
        public bool ProcesarVenta(int idCliente, int idUsuario, int idCaja) {
            return base.Channel.ProcesarVenta(idCliente, idUsuario, idCaja);
        }
        
        public System.Threading.Tasks.Task<bool> ProcesarVentaAsync(int idCliente, int idUsuario, int idCaja) {
            return base.Channel.ProcesarVentaAsync(idCliente, idUsuario, idCaja);
        }
    }
}
