//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceInventarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceInventarios.InventariosSoap")]
    public interface InventariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServiceInventarios.HelloWorldResponse HelloWorld(Bodega_Ventas.ServiceInventarios.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceInventarios.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServiceInventarios.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarValidez", ReplyAction="*")]
        bool VerificarValidez(int prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificarValidez", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> VerificarValidezAsync(int prod);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceInventarios.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServiceInventarios.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceInventarios.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServiceInventarios.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InventariosSoapChannel : Bodega_Ventas.ServiceInventarios.InventariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventariosSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceInventarios.InventariosSoap>, Bodega_Ventas.ServiceInventarios.InventariosSoap {
        
        public InventariosSoapClient() {
        }
        
        public InventariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceInventarios.HelloWorldResponse Bodega_Ventas.ServiceInventarios.InventariosSoap.HelloWorld(Bodega_Ventas.ServiceInventarios.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServiceInventarios.HelloWorldRequest inValue = new Bodega_Ventas.ServiceInventarios.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceInventarios.HelloWorldRequestBody();
            Bodega_Ventas.ServiceInventarios.HelloWorldResponse retVal = ((Bodega_Ventas.ServiceInventarios.InventariosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceInventarios.HelloWorldResponse> Bodega_Ventas.ServiceInventarios.InventariosSoap.HelloWorldAsync(Bodega_Ventas.ServiceInventarios.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceInventarios.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServiceInventarios.HelloWorldRequest inValue = new Bodega_Ventas.ServiceInventarios.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceInventarios.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServiceInventarios.InventariosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public bool VerificarValidez(int prod) {
            return base.Channel.VerificarValidez(prod);
        }
        
        public System.Threading.Tasks.Task<bool> VerificarValidezAsync(int prod) {
            return base.Channel.VerificarValidezAsync(prod);
        }
    }
}
