//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceUtilitarios {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceUtilitarios.UtilitariosSoap")]
    public interface UtilitariosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse HelloWorld(Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento tipo del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Filtros_Extensiones", ReplyAction="*")]
        Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse Filtros_Extensiones(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Filtros_Extensiones", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse> Filtros_ExtensionesAsync(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceUtilitarios.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServiceUtilitarios.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceUtilitarios.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServiceUtilitarios.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Filtros_ExtensionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Filtros_Extensiones", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequestBody Body;
        
        public Filtros_ExtensionesRequest() {
        }
        
        public Filtros_ExtensionesRequest(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Filtros_ExtensionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string tipo;
        
        public Filtros_ExtensionesRequestBody() {
        }
        
        public Filtros_ExtensionesRequestBody(string tipo) {
            this.tipo = tipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Filtros_ExtensionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Filtros_ExtensionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponseBody Body;
        
        public Filtros_ExtensionesResponse() {
        }
        
        public Filtros_ExtensionesResponse(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class Filtros_ExtensionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Filtros_ExtensionesResult;
        
        public Filtros_ExtensionesResponseBody() {
        }
        
        public Filtros_ExtensionesResponseBody(string Filtros_ExtensionesResult) {
            this.Filtros_ExtensionesResult = Filtros_ExtensionesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UtilitariosSoapChannel : Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UtilitariosSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap>, Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap {
        
        public UtilitariosSoapClient() {
        }
        
        public UtilitariosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UtilitariosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitariosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UtilitariosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap.HelloWorld(Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest inValue = new Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceUtilitarios.HelloWorldRequestBody();
            Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse retVal = ((Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse> Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap.HelloWorldAsync(Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest inValue = new Bodega_Ventas.ServiceUtilitarios.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceUtilitarios.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap.Filtros_Extensiones(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest request) {
            return base.Channel.Filtros_Extensiones(request);
        }
        
        public string Filtros_Extensiones(string tipo) {
            Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest inValue = new Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest();
            inValue.Body = new Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequestBody();
            inValue.Body.tipo = tipo;
            Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse retVal = ((Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap)(this)).Filtros_Extensiones(inValue);
            return retVal.Body.Filtros_ExtensionesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse> Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap.Filtros_ExtensionesAsync(Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest request) {
            return base.Channel.Filtros_ExtensionesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesResponse> Filtros_ExtensionesAsync(string tipo) {
            Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest inValue = new Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequest();
            inValue.Body = new Bodega_Ventas.ServiceUtilitarios.Filtros_ExtensionesRequestBody();
            inValue.Body.tipo = tipo;
            return ((Bodega_Ventas.ServiceUtilitarios.UtilitariosSoap)(this)).Filtros_ExtensionesAsync(inValue);
        }
    }
}
