//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bodega_Ventas.ServiceProductos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceProductos.ProductosSoap")]
    public interface ProductosSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        Bodega_Ventas.ServiceProductos.HelloWorldResponse HelloWorld(Bodega_Ventas.ServiceProductos.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.HelloWorldResponse> HelloWorldAsync(Bodega_Ventas.ServiceProductos.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCategoría", ReplyAction="*")]
        Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse InsertarCategoría(Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarCategoría", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse> InsertarCategoríaAsync(Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarSubcategoria", ReplyAction="*")]
        Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse InsertarSubcategoria(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertarSubcategoria", ReplyAction="*")]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse> InsertarSubcategoriaAsync(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(Bodega_Ventas.ServiceProductos.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(Bodega_Ventas.ServiceProductos.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCategoríaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCategoría", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.InsertarCategoríaRequestBody Body;
        
        public InsertarCategoríaRequest() {
        }
        
        public InsertarCategoríaRequest(Bodega_Ventas.ServiceProductos.InsertarCategoríaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCategoríaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string desc;
        
        public InsertarCategoríaRequestBody() {
        }
        
        public InsertarCategoríaRequestBody(string nombre, string desc) {
            this.nombre = nombre;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarCategoríaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarCategoríaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.InsertarCategoríaResponseBody Body;
        
        public InsertarCategoríaResponse() {
        }
        
        public InsertarCategoríaResponse(Bodega_Ventas.ServiceProductos.InsertarCategoríaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarCategoríaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarCategoríaResult;
        
        public InsertarCategoríaResponseBody() {
        }
        
        public InsertarCategoríaResponseBody(string InsertarCategoríaResult) {
            this.InsertarCategoríaResult = InsertarCategoríaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarSubcategoriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarSubcategoria", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequestBody Body;
        
        public InsertarSubcategoriaRequest() {
        }
        
        public InsertarSubcategoriaRequest(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarSubcategoriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cat;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string desc;
        
        public InsertarSubcategoriaRequestBody() {
        }
        
        public InsertarSubcategoriaRequestBody(int cat, string nombre, string desc) {
            this.cat = cat;
            this.nombre = nombre;
            this.desc = desc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertarSubcategoriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertarSubcategoriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponseBody Body;
        
        public InsertarSubcategoriaResponse() {
        }
        
        public InsertarSubcategoriaResponse(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertarSubcategoriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string InsertarSubcategoriaResult;
        
        public InsertarSubcategoriaResponseBody() {
        }
        
        public InsertarSubcategoriaResponseBody(string InsertarSubcategoriaResult) {
            this.InsertarSubcategoriaResult = InsertarSubcategoriaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductosSoapChannel : Bodega_Ventas.ServiceProductos.ProductosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductosSoapClient : System.ServiceModel.ClientBase<Bodega_Ventas.ServiceProductos.ProductosSoap>, Bodega_Ventas.ServiceProductos.ProductosSoap {
        
        public ProductosSoapClient() {
        }
        
        public ProductosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceProductos.HelloWorldResponse Bodega_Ventas.ServiceProductos.ProductosSoap.HelloWorld(Bodega_Ventas.ServiceProductos.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            Bodega_Ventas.ServiceProductos.HelloWorldRequest inValue = new Bodega_Ventas.ServiceProductos.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.HelloWorldRequestBody();
            Bodega_Ventas.ServiceProductos.HelloWorldResponse retVal = ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.HelloWorldResponse> Bodega_Ventas.ServiceProductos.ProductosSoap.HelloWorldAsync(Bodega_Ventas.ServiceProductos.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.HelloWorldResponse> HelloWorldAsync() {
            Bodega_Ventas.ServiceProductos.HelloWorldRequest inValue = new Bodega_Ventas.ServiceProductos.HelloWorldRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.HelloWorldRequestBody();
            return ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse Bodega_Ventas.ServiceProductos.ProductosSoap.InsertarCategoría(Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest request) {
            return base.Channel.InsertarCategoría(request);
        }
        
        public string InsertarCategoría(string nombre, string desc) {
            Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest inValue = new Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.InsertarCategoríaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.desc = desc;
            Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse retVal = ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).InsertarCategoría(inValue);
            return retVal.Body.InsertarCategoríaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse> Bodega_Ventas.ServiceProductos.ProductosSoap.InsertarCategoríaAsync(Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest request) {
            return base.Channel.InsertarCategoríaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarCategoríaResponse> InsertarCategoríaAsync(string nombre, string desc) {
            Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest inValue = new Bodega_Ventas.ServiceProductos.InsertarCategoríaRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.InsertarCategoríaRequestBody();
            inValue.Body.nombre = nombre;
            inValue.Body.desc = desc;
            return ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).InsertarCategoríaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse Bodega_Ventas.ServiceProductos.ProductosSoap.InsertarSubcategoria(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest request) {
            return base.Channel.InsertarSubcategoria(request);
        }
        
        public string InsertarSubcategoria(int cat, string nombre, string desc) {
            Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest inValue = new Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequestBody();
            inValue.Body.cat = cat;
            inValue.Body.nombre = nombre;
            inValue.Body.desc = desc;
            Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse retVal = ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).InsertarSubcategoria(inValue);
            return retVal.Body.InsertarSubcategoriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse> Bodega_Ventas.ServiceProductos.ProductosSoap.InsertarSubcategoriaAsync(Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest request) {
            return base.Channel.InsertarSubcategoriaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Bodega_Ventas.ServiceProductos.InsertarSubcategoriaResponse> InsertarSubcategoriaAsync(int cat, string nombre, string desc) {
            Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest inValue = new Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequest();
            inValue.Body = new Bodega_Ventas.ServiceProductos.InsertarSubcategoriaRequestBody();
            inValue.Body.cat = cat;
            inValue.Body.nombre = nombre;
            inValue.Body.desc = desc;
            return ((Bodega_Ventas.ServiceProductos.ProductosSoap)(this)).InsertarSubcategoriaAsync(inValue);
        }
    }
}
